### ISSUE TITLE
request library is deprecated

### ISSUE THREAD

**Issue by codac** [terenc3/MMM-Tankerkoenig#3]
**Describe the bug**
The request library is deprecated and therefor has been removed as dependency of the current MM version.

**To Reproduce**
Run karsten13/magicmirror Docker, check the Protocol for errors
1. Config File
```
{
            		module: 'MMM-Tankerkoenig',
                        position: "top_left",
            		header: 'Super (E10)',
            		config: {
                        	api_key: "<api-key>",
                                lat: 50.12345,
                                lng: 8.9876,
                                types: ["e10"],
                                radius: 9,
            		}
	        },
```
2. Additional Modules used
yes, but are not relevant here

**Expected behavior**
Module should be updated, without using the request library so that this error wont appear anymore.

**Screenshots**
see additional context

**Additional context**
Error messages are:
[15.07.2021 09:59.46.610] [ERROR] Whoops! There was an uncaught exception...
[15.07.2021 09:59.46.613] [ERROR] Error: Cannot find module 'request'
 code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-Tankerkoenig/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]
[15.07.2021 09:59.46.614] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[15.07.2021 09:59.46.614] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by terenc3** [comment]
The real problem here was that there was no package.json file which would have defined request as dependency. Nevertheless i've replaced request with node-fetch

**Comment by codac** [comment]
perfect, thank you for the fast reply!
